version: '2'

services:
  vault:
      image: vault
      ports:
        - "1234:1234"
      environment:
        - VAULT_DEV_ROOT_TOKEN_ID=87e7784b-d598-44fe-8962-c7c345a11eed
        - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234
        - SKIP_SETCAP=true
        - disable_mlock=true